### ISSUE TITLE
PS2 1.2 Part B

### ISSUE THREAD

**Issue by rebeccajohnson88** [rebeccajohnson88/qss20_slides_activities#10]
For each defendant sentenced by judge_21, you want to construct a "matched group" of defendants who:

- Are the same exact age as the focal defendant (`age_derived`) and
- Are the same gender as the focal defendant (`is_male_derived`) but 
- Differ in race from the focal defendant (`is_black_derived`/`is_white_derived`)

Write a user-defined function to find any/all matched defendants for each focal defendant of judge 21. You can structure the function in various ways but one way is to write a function similar to the class example where we iterate over different DC crimes (focal crimes) and find similar crimes. For this problem, we want to:

- Iterate over unique defendants sentenced by judge 21 (use `CASE_PARTICIPANT_ID` to identify each unique defendant)
- Find other defendants in the judge 21 pool who (1) have a different race from that focal defendant but (2) the same gender and age 

**Concepts and resources**: 

- Slides and activity code on user-defined functions and iterating using list comprehension: https://github.com/rebeccajohnson88/qss20_slides_activities/blob/main/activities/w22_activities/solutions/02_loopsfunctions_solutions.ipynb
- You can either write code in the function to add columns with the attributes of the focal defendant (existing material) or using `pd.merge` to join these on after; we'll be covering `pd.merge` Monday 01.24 but here are last year's slides (slide 17-20) in meantime: https://github.com/rebeccajohnson88/qss20_slides_activities/blob/main/slides/s21_slides/qss20_s21_class4.pdf 

**Hints on output**: 

- Some focal defendants may not have any matches; they can be excluded from the results 
- In the way we wrote our function, each iteration of the function returns a single dataframe; because we execute via list comprehension, the output of this step is a list of dataframes (it's okay if you take a diff approach!)

**Comment by rebeccajohnson88** [comment]
**Question from office hours**: are the defendants eligible to be matched with the focal defendant:

- All defendants in the data
- Other defendants sentenced by judge 21

**Response**: other defendants sentenced by judge 21. To make things more concrete, imagine that there are three defendants sentenced by judge 21: me, Jack, and Eunice. The goal is to first treat me as the focal defendant and the pool eligible to be matched is jack/eunice; then treat Jack as focal, me and eunice are pool, and so on

**Comment by rebeccajohnson88** [comment]
**Question**: what should the output be of part B?
**Response**: we're fine with whatever output for part B (our output was a list of dataframes but diff functions might produce diff things)--- the main goal of this part is just get to the answer for part C so whatever output is fine

**Comment by MarcoAllen1** [comment]
do we use the subsetted data frame from part A of 1.2 to go about this? A little confused because that would be all defendants of judge_21 but only those charged with narcotics related crimes.

**Comment by rebeccajohnson88** [comment]
> do we use the subsetted data frame from part A of 1.2 to go about this? A little confused because that would be all defendants of judge_21 but only those charged with narcotics related crimes.

Yep so it should be the filtered dataframe from part A, so with those restrictions but also restricted to judge_21 and narcotics crimes only. So this is the dimensions of mine going into part B

![image](https://user-images.githubusercontent.com/21369316/150656327-ed4788d2-87ca-4023-924f-5b87388ab08b.png)

**Comment by MarcoAllen1** [comment]
Thanks! Does it matter if I have a different number of columns? My rows match but I have 53 columns rather than 56. Is this just due to differences in creating some intermediate variables? 

I also wanted to ask, for part B, when it says "Differ in race from the focal defendant (is_black_derived/is_white_derived)" does that imply that we only care about cases where the defendant is either white or black? What about other races that judge_21 might act on?

**Comment by rebeccajohnson88** [comment]
> Thanks! Does it matter if I have a different number of columns? My rows match but I have 53 columns rather than 56. Is this just due to differences in creating some intermediate variables?
> 
> I also wanted to ask, for part B, when it says "Differ in race from the focal defendant (is_black_derived/is_white_derived)" does that imply that we only care about cases where the defendant is either white or black? What about other races that judge_21 might act on?

- Fine to have diff cols
- See this part in part A where we note to filter to only is_white_derived = True or is_black_derived = True 

https://github.com/rebeccajohnson88/qss20_slides_activities/issues/7#issuecomment-1018133515

**Comment by m-majumder** [comment]
Should the resulting data frame for each focal defendant include the focal defendant or should it just consist of those that have been matched?

**Comment by rebeccajohnson88** [comment]
> Should the resulting data frame for each focal defendant include the focal defendant or should it just consist of those that have been matched?

it should definitely include the sentence length of the focal defendant in order to be able to later compare that sentence length to each matched defendant --- one route is to retain the focal defendant's id but that col is less essential- see here for example output from later part

https://github.com/rebeccajohnson88/qss20_slides_activities/issues/11#issuecomment-1017882192

**Comment by m-majumder** [comment]
Is it okay to have duplicates in the concatenated data frame? The same matched defendants show up multiple times with different focal defendants, so should we try to only have each defendant only show up once, either as a matched person or a focal defendant?

**Comment by rebeccajohnson88** [comment]
> Is it okay to have duplicates in the concatenated data frame? The same matched defendants show up multiple times with different focal defendants, so should we try to only have each defendant only show up once, either as a matched person or a focal defendant?

good Q!

- all defendants who meet the filtering criteria (judge 21, narcotics, black or white, etc) will be a focal defendant at one point (may or may not have matches)
- the same defendant might be a match for > 1 focal defendant

so yes some ppl will appear multiple times --- either as matches for > 1 focal defendant or as a focal defendant and then a match

**Comment by clairebetzer** [comment]
How many focal matches should we expect to return from the comparison for "CASE_PARTICIPANT_ID == 808109112733"?

**Comment by rebeccajohnson88** [comment]
> How many focal matches should we expect to return from the comparison for "CASE_PARTICIPANT_ID == 808109112733"?

@clairebetzer answer here! https://github.com/rebeccajohnson88/qss20_slides_activities/issues/11#issuecomment-1017882192

**Comment by RainesArt** [comment]
Having trouble figuring out how to grab the columns for the focal participants. I tried to run a loop that was the length of data frame columns but every time I do df.columns.values I get an error saying series doesn't have attribute columns

**Comment by rebeccajohnson88** [comment]
> Having trouble figuring out how to grab the columns for the focal participants. I tried to run a loop that was the length of data frame columns but every time I do df.columns.values I get an error saying series doesn't have attribute columns

tagging @jlau31 after his midterm wraps up!

**Comment by RainesArt** [comment]
I figured it out

**Comment by clairebetzer** [comment]
I'm having two issues with the user-defined functions that I'm testing for the correct output. For the first function, I was able to iterate over the data and create the focal matches, but my output is incorrect from the one posted. From this function, I get a warning about deprecation, which advises me to specify "dtype=object" when creating the ndarray. 

When I attempted another function that iterates over a list of the unique case_participant_id's in the filtered dataset, I'm not able to get any output because of a Value Error that says "Length of values (1) does not match length of index (53)."

Any guidance on which function is worth diving deeper into to figure out the issue? Thank you!

**Comment by RainesArt** [comment]
> I'm having two issues with the user-defined functions that I'm testing for the correct output. For the first function, I was able to iterate over the data and create the focal matches, but my output is incorrect from the one posted. From this function, I get a warning about deprecation, which advises me to specify "dtype=object" when creating the ndarray.
> 
> When I attempted another function that iterates over a list of the unique case_participant_id's in the filtered dataset, I'm not able to get any output because of a Value Error that says "Length of values (1) does not match length of index (53)."
> 
> Any guidance on which function is worth diving deeper into to figure out the issue? Thank you!

You should double-check your subsetting condition when grabbing individuals. make sure you subset with the match not being white if focal persons white or black if the focal persons black. Think of it in two steps. The first subset gets you age and gender. the second subset gets you the age gender race

**Comment by rebeccajohnson88** [comment]
> > I'm having two issues with the user-defined functions that I'm testing for the correct output. For the first function, I was able to iterate over the data and create the focal matches, but my output is incorrect from the one posted. From this function, I get a warning about deprecation, which advises me to specify "dtype=object" when creating the ndarray.
> > When I attempted another function that iterates over a list of the unique case_participant_id's in the filtered dataset, I'm not able to get any output because of a Value Error that says "Length of values (1) does not match length of index (53)."
> > Any guidance on which function is worth diving deeper into to figure out the issue? Thank you!
> 
> You should double-check your subsetting condition when grabbing individuals. make sure you subset with the match not being white if focal persons white or black if the focal persons black. Think of it in two steps. The first subset gets you age and gender. the second subset gets you the age gender race

yep seconding arthur's advice; in terms of which specific function to use, either approach works --- in the solutions we iterate over unique ids but other approaches should also work

the error with the id iteration you point I think relates to you trying to assign something to a dataframe that looks to be 53 rows but then you're assigning something of length 1 and not length 53-- i'd read through this and stop by office hours and/or if still stuck debugging dm the TA on call with a screenshot of your code and the error message - https://www.statology.org/length-of-values-does-not-match-length-of-index/ 

**on call for debugging**: https://docs.google.com/spreadsheets/d/13L6t_3b-V-8pKpPVu7PymdTEvZEvpHf0kTtWnF5XzCY/edit#gid=0**

**Comment by rebeccajohnson88** [comment]
Notes from office hours:

- You shouldn't need to do a for loop inside the function and if you do so there'll be a small deduction; would recommend feeding the function one id and iterating using list comprehension (but fine to do other ways as long as the loop/iteration over defendants isnt inside the function)
- For this error--- `ValueError: Can only compare identically-labeled Series objects.` this relates to comparing a series to another series using `==` rather than a series to a single value. So if the focal defendant's age is 25, for instance, and we're comparing other defendants' ages to that in order to subset to same-age-as-focal defendants, we want to make sure that if our code is structured as `df_others.age == df_focal.age` that the `df_focal.age` is a scalar / single value rather than a series; `df_focal.age.iloc[0]` can help with this

**Comment by afwojcik** [comment]
Should we hard-code the DataFrame of defendants sentenced by judge_21 into our function? Or, should the function be able to take any DataFrame?

**Comment by rebeccajohnson88** [comment]
> Should we hard-code the DataFrame of defendants sentenced by judge_21 into our function? Or, should the function be able to take any DataFrame?

Either is fine! So you'll receive full credit even if name of df is hardcoded but also fine to make the dataframe name a parameter
