### ISSUE TITLE
PS2 1.2 Part C

### ISSUE THREAD

**Issue by rebeccajohnson88** [rebeccajohnson88/qss20_slides_activities#11]
Using the results from Part B, use `pd.concat` or another approach to create a dataframe that compares the (1) race and sentence length for the focal defendant to (2) the sentence length for other defendants. Using this dataframe, show this comparison for focal defendant: `CASE_PARTICIPANT_ID` == `808109112733`

**Comment by rebeccajohnson88** [comment]
**Question from student**: I had a question about 1.2 of PSet 2 but I wasn’t able to submit a question on Github (the button just doesn’t work). I was just wondering how Part C differs from Part B. For Part B, my ouput is several dataframes with focal defendants and their matches. So, how would Part C look different?

**Response**: great question! If your output from part B is dataframes with different focal defendants/their matches, part C asks you to aggregate that into a single dataframe. pd.concat is one way to aggregate (binds the rows); but there are others. Will share screenshot of output below to help

**Comment by rebeccajohnson88** [comment]
Here's our output for that example defendant:

![image](https://user-images.githubusercontent.com/21369316/150414774-e8874ccd-7a30-45c1-b383-12fa4981597f.png)

**Comment by shuyijin927** [comment]
My Participant IDs come out of my data frame in scientific notation (8.081091e+11). Is there a way for me to change the formatting?

**Comment by rebeccajohnson88** [comment]
> My Participant IDs come out of my data frame in scientific notation (8.081091e+11). Is there a way for me to change the formatting?

 I'd use the global solution (pd.options) discussed here: https://stackoverflow.com/questions/17737300/suppressing-scientific-notation-in-pandas

**Comment by shuyijin927** [comment]
> https://stackoverflow.com/questions/17737300/suppressing-scientific-notation-in-pandas

This would create trailing 0s for my participant IDs (808109112733.00), is that fine or should I look for another solution? I tried to set it to .0f but that doesn't work when we later have to calculate proportions. Thanks for your help!

**Comment by rebeccajohnson88** [comment]
> > https://stackoverflow.com/questions/17737300/suppressing-scientific-notation-in-pandas
> 
> This would create trailing 0s for my participant IDs (808109112733.00), is that fine or should I look for another solution? I tried to set it to .0f but that doesn't work when we later have to calculate proportions. Thanks for your help!

any participant format should be fine as long as the subsetting to that id works/as you note as long as it doesn't affect the proportions in the next question. thanks!

**Comment by armon-lotfi** [comment]
Just to clarify, are the only races we are considering/comparing for part c black and white?

**Comment by rebeccajohnson88** [comment]
> Just to clarify, are the only races we are considering/comparing for part c black and white?

Black and white only - noted here! https://github.com/rebeccajohnson88/qss20_slides_activities/issues/7#issuecomment-1018133515

ccing @jlau31 for any follow up q's
