### ISSUE TITLE
PS2 1.2 Part D

### ISSUE THREAD

**Issue by rebeccajohnson88** [rebeccajohnson88/qss20_slides_activities#12]
Using the results from Part C, group by the focal defendant's race and find the proportion of that defendant's matches who had a LONGER sentence than the focal defendant

**Concepts and resources**: can use groupby and agg

- Groupby and agg code: https://github.com/rebeccajohnson88/qss20_slides_activities/blob/main/activities/w22_activities/solutions/00_pandas_datacleaning_solutions.ipynb

**Hints on output**: since we're grouping by race in the full pool, the resulting output should have two values: one for the rate at which Black defendants have matches with higher sentences; another for the rate at which White defendants have matches with higher sentences

**Comment by MarcoAllen1** [comment]
is there any way to do this in just one line? Or are you stuck counting the total entries for each race (saving that) as well as the total match entries with longer sentence lengths and then dividing? Trying to see if there is a more efficient way to do this that I might be missing.

**Comment by rebeccajohnson88** [comment]
> is there any way to do this in just one line? Or are you stuck counting the total entries for each race (saving that) as well as the total match entries with longer sentence lengths and then dividing? Trying to see if there is a more efficient way to do this that I might be missing.

Depending on how your data are structured, you may be able to make more efficient by creating a boolean indicator for `is_higher` and using the np.mean = proportion yes trick :)

**Comment by devanfink** [comment]
For this problem, are we supposed to basically find each unique focal person, count the number of matches with longer sentences than said focal person, count the total number of matches for each focal person and then group by race and compute the rates by race? Not sure if that makes any sense, but I'm trying to figure out exactly what to do here since each focal person has a different number of matches

**Comment by rebeccajohnson88** [comment]
> For this problem, are we supposed to basically find each unique focal person, count the number of matches with longer sentences than said focal person, count the total number of matches for each focal person and then group by race and compute the rates by race? Not sure if that makes any sense, but I'm trying to figure out exactly what to do here since each focal person has a different number of matches

yep that's it! though i think there are some shortcuts related to my response to Marco

In particular, if we have a single dataframe with (1) the focal defendant's sentence length, (2) the sentence length for their match, (3) repeating 2 across all matches as sep rows, if we create the indicator `is_higher` for match sentence length > focal sentence length, we don't need to do anything with the counts you mention. instead, if we group by focal defendant race and find the proportion is_higher that gets us the summary this question is looking for (so a bit less complicated)

**Comment by devanfink** [comment]
right -- I did it both ways and compared and got the same thing for each!

**Comment by ZackNathan** [comment]
Which quantity are we looking for here? To illustrate, say there is
- one defendant with a single match that has a longer sentence, and
- another defendant with two matches, one of which has a longer sentence

Do we want the average rate over the defendants: (1.0 + 0.5)/2 = 0.75
or the total rate over all defendants in the group: 2/3 = 0.67?

**Comment by devpnn** [comment]
for parts C and D (computing difference in sentence vs focal & "longer" vs the focal), is it necessary to do these separately upon the concatenated function result or could we compute these during the function definition for part B?

**Comment by rebeccajohnson88** [comment]
> Which quantity are we looking for here? To illustrate, say there is
> 
> * one defendant with a single match that has a longer sentence, and
> * another defendant with two matches, one of which has a longer sentence
> 
> Do we want the average rate over the defendants: (1.0 + 0.5)/2 = 0.75 or the total rate over all defendants in the group: 2/3 = 0.67?

good flag! i think in practice either is fine as long as you're clear about which

sorry for delay- needed to walk through it. the solutions we have correspond to this one: `the total rate over all defendants in the group: 2/3 = 0.67` so if one were to do it a longer way it'd be something like:

- separate out the black from the white focal defendants
- within the black focal defendants, the denom is total rows (so each black defendant is multiplied by 1 or more matches)
- within the black focal defendants, the num is the count of those rows where the match has a longer sentence than focal
- divide num/denom
- repeat for white

so yes i think it effectively means that our unit of analysis is the defendant-match dyad and defendants with >1 matches are repeated across rows and the aggregation follows the above logic

**Comment by rebeccajohnson88** [comment]
> for parts C and D (computing difference in sentence vs focal & "longer" vs the focal), is it necessary to do these separately upon the concatenated function result or could we compute these during the function definition for part B?

nope fine if you had that step inside the function! one flag is we actually don't need to find the numeric difference between the days - just binary longer or not
