### ISSUE TITLE
PS3 1.3.1  

### ISSUE THREAD

**Issue by rebeccajohnson88** [rebeccajohnson88/qss20_slides_activities#18]
### 1.3.1 Converting to upper (2 points)

A. Convert the names `EMPLOYER_NAME` and `Name` to uppercase using list comprehension rather than df.varname.str.upper() (it's fine to do a separate list comprehension line for each of the two columns)

B. Print a random sample of 15 values of each result

C. Assign the full vector of uppercase names back to the original data, writing over the original `EMPLOYER_NAME` and `Name` columns 

**Resources**:
    - Activity code with list comprehension: https://github.com/rebeccajohnson88/qss20_slides_activities/blob/main/activities/w22_activities/solutions/00_pandas_datacleaning_solutions.ipynb 
    - Sampling from a list without replacement using the `random` module: https://note.nkmk.me/en/python-random-choice-sample-choices/ 

**Output**: since everyone's random sample will be different, we don't have a uniform output; here's an example of the uppercase conversion for the American Crawfish employer in `jobs`: `AMERICAN CRAWFISH LLC`

![image](https://user-images.githubusercontent.com/21369316/152060444-350ae2a4-f660-40e6-8e26-1a1558868444.png)

**Comment by shuyijin927** [comment]
To clarify, we will have two lists (one for each column)? 

yep one list of `EMPLOYER_NAME`; another for `Name`

**Comment by rebeccajohnson88** [comment]
Student had good question in office hours about this line: `Assign the full vector of uppercase names back to the original data, writing over the original EMPLOYER_NAME and Name columns`

The "vector" language was imprecise on my part (lapsed into R-speak!)- this will be a list of uppercase names

**Comment by tarapillai** [comment]
Is it okay to do part A and C in one line or do I need to make two lists?

**Comment by rebeccajohnson88** [comment]
> Is it okay to do part A and C in one line or do I need to make two lists?

fine if combined as long as you print a sample of just that col - thanks!
