### ISSUE TITLE
PS3 1.3.2 Part C

### ISSUE THREAD

**Issue by rebeccajohnson88** [rebeccajohnson88/qss20_slides_activities#20]
C. Use that pattern in conjunction with `re.sub` and list comprehension to clean the columns in each dataset. Save the new columns as `name_clean` in each. Then, use row subsetting to (1) subset to rows that changed names and for:

- `debar` print the `Name` and `name_clean` columns
- `jobs` print the `EMPLOYER_NAME` and `name_clean` columns

Make sure to use the uppercase versions of the variables

**Concepts and resources**: for the last part of row subsetting and printing two columns in each dataframe, use the `.loc` examples shown here: https://github.com/rebeccajohnson88/qss20_slides_activities/blob/main/activities/w22_activities/solutions/00_pandas_datacleaning_solutions.ipynb

**Output**:

Head of changed employer names in jobs (your head may be different depending on order of data)

![image](https://user-images.githubusercontent.com/21369316/151913329-1416db08-3c59-4c13-8c93-af3e40d19b76.png)

Head of changed employer names in debar:

![image](https://user-images.githubusercontent.com/21369316/151913387-b77eab6c-c5d0-4b76-80f2-70442861483c.png)

**Comment by MarcoAllen1** [comment]
Is there a reason that my head might be different? It seems like it worked for me but my debar starts with j&j harvesting and jobs with FAZIO FARMS OPERATING COPANY, LLC

**Comment by rebeccajohnson88** [comment]
> Is there a reason that my head might be different? It seems like it worked for me but my debar starts with j&j harvesting and jobs with FAZIO FARMS OPERATING COPANY, LLC

fine to have different head! what's your dimension when you run .shape?

**Comment by MarcoAllen1** [comment]
> > Is there a reason that my head might be different? It seems like it worked for me but my debar starts with j&j harvesting and jobs with FAZIO FARMS OPERATING COPANY, LLC
> 
> fine to have different head! what's your dimension when you run .shape?

I get debar with (11,2) and jobs with (575,2). Sound about right?

**Comment by rebeccajohnson88** [comment]
> > > Is there a reason that my head might be different? It seems like it worked for me but my debar starts with j&j harvesting and jobs with FAZIO FARMS OPERATING COPANY, LLC
> > 
> > 
> > fine to have different head! what's your dimension when you run .shape?
> 
> I get debar with (11,2) and jobs with (575,2). Sound about right?

hm so i think at this stage the data should still be the same shape as it is at read in in first cell, so this; lmk if u have different dims at the read-in stage

![image](https://user-images.githubusercontent.com/21369316/152228670-94b72dec-ad61-42ce-b37f-2a00d47385bf.png)

**Comment by MarcoAllen1** [comment]
> > > > Is there a reason that my head might be different? It seems like it worked for me but my debar starts with j&j harvesting and jobs with FAZIO FARMS OPERATING COPANY, LLC
> > > 
> > > 
> > > fine to have different head! what's your dimension when you run .shape?
> > 
> > 
> > I get debar with (11,2) and jobs with (575,2). Sound about right?
> 
> hm so i think at this stage the data should still be the same shape as it is at read in in first cell, so this; lmk if u have different dims at the read-in stage
> 
> ![image](https://user-images.githubusercontent.com/21369316/152228670-94b72dec-ad61-42ce-b37f-2a00d47385bf.png)

oh sorry! Those were the dimensions just subsetted for the ones that were changed in Debar/jobs! (as in they had a . removed)
