### ISSUE TITLE
PS4 1.2 D, E

### ISSUE THREAD

**Issue by rebeccajohnson88** [rebeccajohnson88/qss20_slides_activities#29]
D. You want to extract the possible sentence lengths the CEO is facing; pull out the named entities with (1) the label `DATE` and (2) that contain the word year or years (hint: you may want to use the `re` module for that second part). Print these named entities.

E. Pull and print the original parts of the press releases where those year lengths are mentioned (e.g., the sentences or rough region of the press release). Describe in your own words (1 sentence) what length of sentence (prison) and probation (supervised release) the CEO may be facing if convicted after this indictment (if there are multiple lengths mentioned describe the maximum). *Hint*: you may want to use re.search or re.findall 

**Output for D**:

![image](https://user-images.githubusercontent.com/21369316/153986845-49eb7b51-72ae-4e41-96fa-4d7925c2ee44.png)

**Output for E**:

![image](https://user-images.githubusercontent.com/21369316/153986888-161d2351-d966-4b87-a2f5-40c128e692b0.png)

**Comment by devanfink** [comment]
Quick question here: My output is returning just "five years" rather than "no greater than five years." I went back into the topic modeling and it seems like it's spaCy that isn't picking up the "no greater than" part of the string. Is there something I need to fix, or is this just how it ran on my machine?

**Comment by rebeccajohnson88** [comment]
> Quick question here: My output is returning just "five years" rather than "no greater than five years." I went back into the topic modeling and it seems like it's spaCy that isn't picking up the "no greater than" part of the string. Is there something I need to fix, or is this just how it ran on my machine?

great q! this is fine and just likely relates to different versions of SpaCy across machines

**Comment by pattanadeen** [comment]
For part E, do we need the use re.findall for each of the entities we found in part D? For example, I use re.findall to find 'last year' and print out the context around 'last year' out. In this case, I have to do the same thing 5 times. Do I understand this part E correctly?

**Comment by rebeccajohnson88** [comment]
> For part E, do we need the use re.findall for each of the entities we found in part D? For example, I use re.findall to find 'last year' and print out the context around 'last year' out. In this case, I have to do the same thing 5 times. Do I understand this part E correctly?

sorry for late reply! you should be able to write a single pattern that combines different things to detect using "or" logic so runs in one line of code/pattern detection rather than 5 lines

**Comment by clairebetzer** [comment]
I'm having an issue when I try to execute the regex pattern in list comprehension over the date-labeled entities. My regex pattern works on example code, but my output is an empty string when I try to execute it over the named entities. Any advice on why this is happening?

**Comment by clairebetzer** [comment]
> I'm having an issue when I try to execute the regex pattern in list comprehension over the date-labeled entities. My regex pattern works on example code, but my output is an empty string when I try to execute it over the named entities. Any advice on why this is happening?

Figured this out with help from Jack!
