### ISSUE TITLE
PS4 3 A and B

### ISSUE THREAD

**Issue by rebeccajohnson88** [rebeccajohnson88/qss20_slides_activities#36]
# 3. Extend the analysis from unigrams to bigrams (10 points)

In the previous question, you found top words via a unigram representation of the text. Now, we want to see how those top words change with bigrams (pairs of words)

A. Using the `doj_subset_wscore` data and the `processed_text` column (so the words after stemming/other preprocessing), create a column in the data called `processed_text_bigrams` that combines each consecutive pairs of word into a bigram separated by an underscore. Eg:

"depart reach settlem" would become "depart_reach reach_settlem"

Do this by writing a function `create_bigram_onedoc` that takes in a single `processed_text` string and returns a string with its bigrams structured similarly to above example
 
**Hint**: there are many ways to solve but `zip` may be helpful: https://stackoverflow.com/questions/21303224/iterate-over-all-pairs-of-consecutive-items-in-a-list

B. Print the `id`, `processed_text`, and `processed_text_bigram` columns for press release with id = 16-217

**Output from example (fine if yours differs slightly)**:

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/21369316/154125845-804fcbd0-ca7d-4450-93d7-ccfbef77f3e0.png">

**Comment by clairebetzer** [comment]
When I execute the code for the bigram function outside of the function, I'm able to get the correct output. But, putting it inside the function yields a lot of "Nones," and executing list comprehension outputs one of the example sets of bigrams. I restarted the kernel with the example code hashed out, and it still outputs. Any advice as to why this is happening?

**Comment by rebeccajohnson88** [comment]
> When I execute the code for the bigram function outside of the function, I'm able to get the correct output. But, putting it inside the function yields a lot of "Nones," and executing list comprehension outputs one of the example sets of bigrams. I restarted the kernel with the example code hashed out, and it still outputs. Any advice as to why this is happening?

hm I'd probably:
- add `print` statements inside the function to see where it's yielding none's
- the nones suggest something is being lost when you're pasting together stuff so i think print should help
- if can't figure out then dm me and eunice w/ screenshot of code and output
