### ISSUE TITLE
PS2 1.1 Part A

### ISSUE THREAD

**Issue by rebeccajohnson88** [rebeccajohnson88/qss20_slides_activities#7]
- Read in the data
- Filter to sentences that involve incarceration (same Illinois Department of Corrections logic as in problem set one: 
incarceration is indicated by `COMMITMENT_TYPE` == "Illinois Department of Corrections")
- Using the `COMMITMENT_UNIT` column that represents sentence length, filter out the following non-numeric sentence lengths: Term, Pounds, Dollars, Ounces (year, months, natural life, days, hours, and weeks should remain)
- Filter to Black or White defendants

**Concepts tested and resources**: this question tests filtering rows based on logical conditions. Here are some resources:
- DataCamp on .loc: https://campus.datacamp.com/courses/data-manipulation-with-pandas/slicing-and-indexing-dataframes?ex=3
- Lecture 2 slide 19: https://campus.datacamp.com/courses/data-manipulation-with-pandas/slicing-and-indexing-dataframes?ex=3 
- Row subsetting section in this activity: https://github.com/rebeccajohnson88/qss20_slides_activities/blob/main/activities/w22_activities/solutions/00_pandas_datacleaning_solutions.ipynb

**Hints on output**: we get 58289 rows remaining after this filtering. Don't worry about matching this exactly but try to get in the ballpark range.

**Comment by rebeccajohnson88** [comment]
**Clarification from office hours**: please use the `sentencing_cleaned.pkl` or `sentencing_cleaned.csv` file --- so the data you used in pset one part two --- rather than the raw data you used at the begining of pset 1

**Comment by afwojcik** [comment]
How do we consider Hispanic defendants when filtering to Black or White defendants?

**Comment by rebeccajohnson88** [comment]
> How do we consider Hispanic defendants when filtering to Black or White defendants?

@afwojcik just consider as Black or white: either `is_white_derived` is true or `is_black_derived` is true (so we're just relying on the earlier codings that go into the sentencing_cleaned data you read in)

**Comment by RainesArt** [comment]
What is considered a ballpark range of rows?

**Comment by rebeccajohnson88** [comment]
> What is considered a ballpark range of rows?

I think actually the rows should match exactly if you're doing things right (otherwise something is off and so ballpark would mean only small deduction)- feel free to stop by OH or dm the on-call person w/ code screenshot if not exact match

**Comment by RainesArt** [comment]
I just misread the last part black or white thought it was one or the other

**Comment by rebeccajohnson88** [comment]
> I just misread the last part black or white thought it was one or the other

ah yea so you will probably use "or" syntax but data will retain _both_ black and white defendants (so just filtering out def in other racial/ethnic categories)
