### ISSUE TITLE
PS2 1.1 Part B

### ISSUE THREAD

**Issue by rebeccajohnson88** [rebeccajohnson88/qss20_slides_activities#8]
Then, follow the instructions in the codebook (combining `COMMITMENT_TERM` with `COMMITMENT_UNIT`) to create a standard sentence length in days column (`senlength_derived`) that measures the sentence in **days**. To simplify, you can assume that:

- 1 hour = 1/24th of a day
- 1 year = 365 days
- 1 month = 30.5 days
- 1 week = 7 days
- Natural life = difference between the age of 100 and the defendant's age at incident (cleaned; if missing, code to age 20); note that this is a simplification since age at incident != age at sentencing 

Print the following cols for an example of each type (eg an example of originally hours; an example of natural life): `COMMITMENT_TERM`, `COMMITMENT_UNIT`, `age_derived` and your new standardized sentence length column (`senlength_derived`)

Print the summary of that column (`senlength_derived`) using the .describe() command

**Concepts tested and resources**: there are many approaches but a couple ways are:
- np.select covered in the slides and this activity notebook: https://github.com/rebeccajohnson88/qss20_slides_activities/blob/main/activities/w22_activities/solutions/00_pandas_datacleaning_solutions.ipynb 
- writing a function that takes in one row as an argument and has a series of if, elif, else conditions where different commitment_units are translated into days. To execute this function, you can use the .apply function but apply it with axis = 1 (row-wise). Resources for that include: (1) the activity notebook on user-defined functions (https://github.com/rebeccajohnson88/qss20_slides_activities/blob/main/activities/w22_activities/solutions/02_loopsfunctions_solutions.ipynb); (2) the activity notebook covering apply: https://github.com/rebeccajohnson88/qss20_slides_activities/blob/main/activities/w22_activities/solutions/00_pandas_datacleaning_solutions.ipynb

**Hint on output**: see GitHub issue for the summary stats we get from running .describe()

![image](https://user-images.githubusercontent.com/21369316/150023415-c4defff4-c4d2-48fe-b70f-817b86a9b968.png)

**Comment by devanfink** [comment]
Hi Prof. Johnson + TAs: I ran the describe function for my code and found to be ever-so-slightly off on the mean, standard deviation, and 25th percentile for my senlength_derived variable. I checked a few individual cases and couldn't seem to figure out exactly what was different -- how do you best recommend reconciling this?

**Comment by rebeccajohnson88** [comment]
**Clarification**: for this part of the question:


Print the following cols for an example of each type (eg an example of originally hours; an example of natural life): COMMITMENT_TERM, COMMITMENT_UNIT, age_derived and your new standardized sentence length column (senlength_derived)


You'll get some credit if you get the sample via code like the following:

```
df.loc[df.COMMITMENT_UNIT == "Hours", ['COMMITMENT_UNIT', 'COMMITMENT_TERM', 
                        'age_derived', 'senlength_derived'][.sample(1)
df.loc[df.COMMITMENT_UNIT == "Days", ['COMMITMENT_UNIT', 'COMMITMENT_TERM', 
                        'age_derived', 'senlength_derived'][.sample(1)
and so on
```

But for full credit, because the above code is highly inefficient (it copies and pastes the same line of code 6 times, one for each type of commitment, find a way to do this more efficiently via something like a user-defined function, groupby, or other approach

**Comment by MarcoAllen1** [comment]
Rather than write age_derived, I just rewrote AGE_AT_INCIDENT in the necessary format. is this okay to do? It seems like all works fine with the hints, but I don't really know how to convert back at this point, so i wanted to see if it was okay to leave it as is.

**Comment by rebeccajohnson88** [comment]
> Rather than write age_derived, I just rewrote AGE_AT_INCIDENT in the necessary format. is this okay to do? It seems like all works fine with the hints, but I don't really know how to convert back at this point, so i wanted to see if it was okay to leave it as is.

hm yea for standardization of results i'd use the `age_derived` column we provide in the cleaned data and alter that; you can undo changes by restarting the kernel and reading in the data again
