### ISSUE TITLE
PS2 1.2 Part A

### ISSUE THREAD

**Issue by rebeccajohnson88** [rebeccajohnson88/qss20_slides_activities#9]
Keep the above ~58k row dataset that is subsetted to only to sentences involving incarceration. Then, further subset the rows to:
- Rows where `judgeid_derived` = `judge_21` 
- `simplified_offense_derived` == "Narcotics"

Use `shape` to print the dimensions of the resulting dataframe

**Concepts and resources**: row subsetting using logical conditions; see above resources

**Hint on output**: we get 53 rows after this filtering step. Don't worry about matching this exactly but try to get in the ballpark range.

**Comment by vickymei1** [comment]
test test
